# Generated by Django 4.2.7 on 2025-07-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
