# Generated by Django 4.2.6 on 2025-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0006_flyer_image_alter_flyer_pdf'),
        ('accounts', '0005_remove_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='providers', to='flyers.store'),
        ),
    ]
