# Generated by Django 5.2.3 on 2025-08-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
