# Generated by Django 4.2.7 on 2025-07-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0003_providerapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerapplication',
            old_name='city',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='providerapplication',
            old_name='has_website',
            new_name='reviewed',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='country',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='name',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='state',
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='address',
            field=models.TextField(default='Not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='document',
            field=models.FileField(default='placeholder.pdf', upload_to='provider_docs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='providerapplication',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
       
        migrations.AlterField(
            model_name='providerapplication',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
