# Generated by Django 4.2.7 on 2025-07-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0004_rename_city_providerapplication_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='company_size',
        ),
    ]
