# Generated by Django 4.2.6 on 2025-07-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0005_remove_providerapplication_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flyers/images/'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='flyers/pdfs/'),
        ),
    ]
