# Generated by Django 4.2.6 on 2025-07-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0006_flyer_image_alter_flyer_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flyers.store'),
        ),
    ]
