# Generated by Django 4.2.6 on 2025-07-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0007_providerapplication_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='store',
        ),
    ]
