# Generated by Django 4.2.6 on 2025-07-25 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flyers', '0008_remove_providerapplication_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_stores', to=settings.AUTH_USER_MODEL),
        ),
       
    ]
