# Generated by Django 4.2.6 on 2025-07-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0009_store_provider_alter_providerapplication_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pending_flyers/pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pending_flyers/images/')),
                ('expires_at', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flyers.region')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyers.store')),
            ],
        ),
    ]
