# Generated by Django 5.2.3 on 2025-08-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0010_pendingflyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pendingflyer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
