# Generated by Django 5.2.3 on 2025-08-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0011_flyer_slug_pendingflyer_slug_product_slug_store_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flyer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pendingflyer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
    ]
