# Generated by Django 5.2.3 on 2025-08-28 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0013_country_slug_flyer_slug_pendingflyer_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='flyers.region'),
        ),
    ]
