# Generated by Django 5.2.3 on 2025-08-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyers', '0013_country_slug_flyer_slug_pendingflyer_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='gender',
        ),
    ]
